### ISSUE TITLE
Add comment on generated code

### ISSUE THREAD

**Issue by b00f** [Pactus-Contrib/jrpc-gateway#5]
Please add some comment on generated code. As reference look at [here](https://github.com/pactus-project/pactus/blob/1adfdc49ff7292bfafa4c5b566eb4e5c3d3cdeea/www/grpc/gen/go/blockchain.pb.gw.go#L583)

**Comment by ja7ad** [comment]
Fixed https://github.com/PacViewer/jrpc-gateway/commit/05f5f1a2764accbe3be17ea2dfd7082cf78fc4bb
